# Generated by Django 5.2 on 2025-05-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_hw8', '0003_alter_subtask_status_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
